# -*- coding: utf-8 -*-
"""quiz.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vQIcO-h8NkKR6SyrwTxWBnad4OBwf136
"""

kullanici1 = {
    'ad': 'Ferhat',
    'soyad': 'Ibrik',
    'uzmanlik': ['Front-End']
}
kullanici2 = {
    'ad': 'Gokce',
    'soyad': 'Gün',
    'uzmanlik': ['Tasarim']
}
kullanici3 = {
    'ad': 'Mesut',
    'soyad': 'Gün',
    'uzmanlik': ['Front-End']
}

# Soru 1: Ferhat Ibrik Kullanicisinin uzmanlik alanlarini döndür
kullanici1["uzmanlik"]

kullanici_listesi = [kullanici1, kullanici2, kullanici3] 

# Soru 2: Front-end alanindaki uzmanlarin isimlerini döndür
for x in kullanici_listesi:
        if x.get("uzmanlik") == ["Front-End"]:
            print(x["ad"])

# Soru 3: Mesut kullanicisi Yazilim ögrendi, bilgileri güncelle!
kullanici3["uzmanlik"].append("Yazilim")
print(kullanici3)

# Soru 4: 1den fazla uzmanlik alani olan kullanicilari döndür (Hint: length)
for x in kullanici_listesi:
        if len(x["uzmanlik"])>1:
            print(x)

kullanici_yaslari_listesi = [22, 34, 32]
# Soru 5: zip kullanarak iki listeyi birlestir ve yasi 30'dan az olan kullanicilar kimler?
for x,kul in zip(kullanici_listesi,kullanici_yaslari_listesi):
    if kul < 30:
        print(x)

# Soru 6: deger isimli degiskene atanan sayinin asal olup olmadigini söyle!
# Hint Asal sayi: kendinden ve 1'den baska böleni olmayan sayilar örnek 2,3,5,7

deger = 4
x=deger-1
while x>1:
    if deger%x==0:
        print(f"{deger} sayisi asal değildir")
        break
    else:
        x-=1
else:
    print(f"{deger} sayisi asaldır")